name: cgc-tutorial

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - pip:
      - aiohttp
      - requests
      - xarray
      - zarr
      - clustering-geodata-cubes
